# Generated by Django 3.0.6 on 2020-05-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSignup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('join_code', models.CharField(max_length=50, null=True)),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
    ]
